version: '3.7'
services:
  web:
    build: ./app
    command: gunicorn highload_django.wsgi -b  0.0.0.0:5000
    restart: always
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=highload_django
      - POSTGRES_PASSWORD=highload_django
      - POSTGRES_DB=mereke
volumes:
  postgres_data: