version: '3.7'
services:
  web:
    build: ./app
    command: gunicorn highload_django.wsgi -b  0.0.0.0:4000
    restart: always
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 4000:4000
    env_file:
      - ./.env.dev
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
volumes:
  postgres_data: